### ISSUE TITLE
image_sourcefile = 'train-images-boxable-with-rotation.csv' not found.

### ISSUE THREAD

**Issue by meet-VC** [bethgelab/openimages2coco#3]
I am trying to follow the installation steps. 

**Current folder structure:**
**Custom_dataset:**
    - annotations
    - cocoapi
    - openimages2coco
    - train
    - test
    - val

**The annotations folder consist of 4 files:** 
    - class-descriptions-boxable.csv
    - test-annotations-bbox.csv
    - train-annotations-bbox.csv
    - validation-annotations-bbox.csv

![Screenshot from 2020-10-05 17-51-06](https://user-images.githubusercontent.com/69953044/95078998-a2251d80-0733-11eb-980f-f2cac1b2008b.png)

Can you please let me know from where to download "train-images-boxable-with-rotation.csv" file? 

Also, can you please tell me which is i have any mistake in my command:
`python convert_annotations.py -p ../ --task bbox`

**Comment by Noobzik** [comment]
So, how did you fixed your issue ? I se that you closed the issue

**Comment by meet-VC** [comment]
Please use this link : https://storage.googleapis.com/openimages/web/download.html 

And Download all files from _download the annotations and metadata_ section. 

Currently, I have the following files in my annotations folder:
 --------------------------------------------------------------------------
- train-annotations-human-imagelabels-boxable.csv
- validation-annotations-human-imagelabels-boxable.csv
- test-annotations-human-imagelabels-boxable.csv
--------------------------------------------------------------------------
- train-annotations-bbox.csv
- validation-annotations-bbox.csv
- test-annotations-bbox.csv
--------------------------------------------------------------------------
- train-images-boxable-with-rotation.csv
- validation-images-with-rotation.csv
- test-images-with-rotation.csv
 --------------------------------------------------------------------------
- class-descriptions-boxable.csv
- validation-annotations-object-segmentation.csv

Once all the files are downloaded using the following command from base directory being openimages2coco/ :

`Exaple script: python convert_annotations.py -p ../ --subset validation --categories Car Cat Dog`

**Comment by EllisHui** [comment]
![1](https://user-images.githubusercontent.com/42332058/122203760-f2629b00-ced0-11eb-913d-2defdb057bae.png)
![2](https://user-images.githubusercontent.com/42332058/122203771-f7bfe580-ced0-11eb-8357-30b0e64e09f1.png)
![3](https://user-images.githubusercontent.com/42332058/122203789-fb536c80-ced0-11eb-861f-6c0e218deddc.png)
![5](https://user-images.githubusercontent.com/42332058/122203809-ff7f8a00-ced0-11eb-800c-8abd2c4885f2.png)
![9](https://user-images.githubusercontent.com/42332058/122203825-03131100-ced1-11eb-96eb-3a18af35739c.png)

**Comment by EllisHui** [comment]
Hello,Thanks for your answer！But i have two questions like above,can you give me some improve suggestions?
if you can ,i will be grateful
