### ISSUE TITLE
Not able to find train_sizes-00000-of-00001.csv 

### ISSUE THREAD

**Issue by chihyaoma** [bethgelab/openimages2coco#5]
Hi, 

Thanks for sharing the script for converting annotations to COCO format. I am going through your code but realized that I am not able to find a particular file `train_sizes-00000-of-00001.csv`. 

Do you mind sharing with me where can I download it?

Thank you!

**Comment by Major-Yuan** [comment]
Hi,

have you found where are train_sizes-00000-of-00001.csv and validation_sizes-00000-of-00001.csv?

thanks!!
